<?php

namespace Vputi\TripBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripRepository extends EntityRepository
{
    public function findLast($created)
    {
        $query = $this->createQueryBuilder('t')
            ->where('t.created > :created')
            ->andWhere('t.timeDeparture > CURRENT_DATE()')
            ->setParameter('created', $created)
            ->orderBy('t.created', 'DESC')
            ->setMaxResults(5)
            ->getQuery();

        return $query->getResult();
    }

    public function findActive($limit)
    {
        $query = $this->createQueryBuilder('t')
            ->andWhere('t.timeDeparture > CURRENT_DATE()')
            ->orderBy('t.created', 'DESC')
            ->setMaxResults($limit)
            ->getQuery();

        return $query->getResult();
    }
}
