trip:
    resource: "@TripBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

#event_api:
#    type: rest
#    prefix: /api
#    resource: "@EventBundle/Resources/config/routing.yml"

home:
    path: /{_locale}
    defaults: { _controller: MainBundle:Main:home, _locale: ru}
    requirements:
        _locale:  en|ru|ua

user:
    resource:   "@UserBundle/Resources/config/routing.yml"
    prefix:     /{_locale}/
    defaults:   { _locale: ru }
    requirements:
        _locale:  en|ru|ua