EventBundle_event:
        resource: "@EventBundle/Resources/config/routing/event.yml"
        prefix:   /events

event_bundle_api:
    type: rest
    prefix: api/v1
    resource: "Vputi\EventBundle\Controller\ApiController"

