parameters:
#    rest_api.example.class: Vputi\RestApiBundle\Example

services:
#    rest_api.example:
#        class: %rest_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
